### ISSUE TITLE
Access to /usercp.php?action=relationships not restricted by plugin settings

### ISSUE THREAD

**Issue by kawaii** [kawaiiforums/mybb-itscomplicated#1]
Users who are unable to send or receive relationship requests are still able to access the `/usercp.php?action=relationships` page. Either the menu item should be removed/hidden, or a permissions error should be displayed.

**Comment by dvz** [comment]
Should users with no permissions still be able to manage their previously created relationships? In this case a message on top might be better.

**Comment by kawaii** [comment]
Good question. In that case we should display a message, and remove (or grey-out) the `Add Relationship`, `Relationship Requests Received` and `Relationship Requests Sent` modules from the page.
