### ISSUE TITLE
Language strings with variables per relationship type

### ISSUE THREAD

**Issue by kawaii** [kawaiiforums/mybb-itscomplicated#9]
Currently, a relationship is shown on the profile like so;
```
kawaii (Married)
```
I feel like we should add a column to the `itscomplicated_relationship_types` table so that an administrator can set a custom language string for each type (we will also provide defaults with this enhancement for the standard types that come with the plugin). For example;
```
Married to {user}, since {since_date}.
```
```
In a relationship with {user}, since {since_date}.
```
This will give administrators a much greater level of flexibility with regards to defining truly custom relationship types on their forums.

**Comment by kawaii** [comment]
Just a side note - this somewhat depends on #2 being implemented beforehand in order to actually display the 'since date' on profiles in the first place.

**Comment by kawaii** [comment]
Another thought that just crossed my mind for a future extension - relationships where the positions held are not necessarily equal, for example;
```
Owned by {user}, since {since_date}.
```
```
Master of {user}, since {since_date}.
```
Not quite sure how best this should be implemented however.

**Comment by dvz** [comment]
It might be best to bundle the features of custom strings and sub-types together then.

A Relationship Type would have possible Roles - presumably assigned by the request initiator - with translatable titles (like Types), which by default would use the general format of `[Type] ([Role])` (_Bob — Mentorship (Student)_).

Completely custom strings will depend on roles of both members to describe the relation (`n` Roles in a Relationship would need `n(n-1)/2` custom strings), so it might be a good time to introduce IDs to avoid complex forms in ACP and assume the language string key format:
```
itscomplicated_relationships_type_[Type ID]_[Role 1 ID]_[Role 2 ID]
```
which would result in:
```
$l['itscomplicated_relationships_type_mentorship'] = 'Mentorship';
$l['itscomplicated_relationships_type_mentorship_role_protege'] = 'Protege';
$l['itscomplicated_relationships_type_mentorship_role_mentor'] = 'Mentor';
$l['itscomplicated_relationships_type_mentorship_protege_to_mentor'] = 'protege of {1}';
$l['itscomplicated_relationships_type_mentorship_mentor_to_protege'] = 'mentor of {1}';
```
if the last 2 don't exist, the general format would be used.

Relationships with more than 2 users would take more advantage of this solution, even though the plugin doesn't support it at the moment.

**Comment by kawaii** [comment]
@dvz do you think it's too much work and refactoring at this point to apply permissions to relationship types? i.e. only allowing certain usergroups access to certain types (which could then include the 'Custom' meta-relationship where the sender defines the roles and language string)?
